const mongoose = require('mongoose')

const formSchema = mongoose.Schema(
{
    email: {
        type: String,
        required: true,
    },
    heist_in_vit:{
        team_name:{
            type:String,
            default:"none"
        },
        leader:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            }
        },
        member1:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            }
        },
        member2:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            }
        },
        member3:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            }
        },
        member4:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            }
        }
    },
    kbc:{
        name:{
            type:String,
            default:"none"
        },
        phone:{
            type:String,
            default:"none"
        },
        college:{
            type:String,
            default:"none"
        }
    },
    brainfunk:{
        name:{
            type:String,
            default:"none"
        },
        phone:{
            type:String,
            default:"none"
        },
        college:{
            type:String,
            default:"none"
        }
    },
    sharks_tank:{
        company_name:{
            type:String,
            default:"none"
        },
        ceo:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            }
        },
        member1:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            },
            role:{
                type:String,
                default:"none"
            }
        },
        member2:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            },
            role:{
                type:String,
                default:"none"
            }
        },
        member3:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            },
            role:{
                type:String,
                default:"none"
            }
        },
        member4:{
            name:{
                type:String,
                default:"none"
            },
            email:{
                type:String,
                default:"none"
            },
            phone:{
                type:String,
                default:"none"
            },
            college:{
                type:String,
                default:"none"
            },
            role:{
                type:String,
                default:"none"
            }
        }
    },
       
},
{
    timestamps: true,
}
);

const Form = mongoose.model('Form', formSchema);

module.exports = Form;